### ISSUE TITLE
pybatfish Github Actions

### ISSUE THREAD

**Issue by jasonyates** [batfish/pybatfish#835]
I'm running a self-hosted GH Action runner in a docker container with steps as follows

```
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pybatfish

      - name: Batfish Prechecks
        run: |
          python pybatfish.py
```

The pybatfish.py script is known-good as running it locally is successful. However when it runs inside of the action runner it fails with the following error

```
Traceback (most recent call last):
  File "pybatfish.py", line 3, in <module>
    from pybatfish.client.session import Session
  File "/tmp/github-runner-your-repo/ci-network-dev/ci-network-dev/pybatfish.py", line 3, in <module>
    from pybatfish.client.session import Session
ModuleNotFoundError: No module named 'pybatfish.client'; 'pybatfish' is not a package
Error: Process completed with exit code 1.
```

If I attach to the docker container, pybatfish is installed 

```
root@afd2723e6afc:/tmp/github-runner-your-repo/ci-network-dev/ci-network-dev# /opt/hostedtoolcache/Python/3.8.12/x64/bin/pip3 install pybatfish
Requirement already satisfied: pybatfish in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (2022.3.16.1242)
Requirement already satisfied: PyYAML in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (6.0)
Requirement already satisfied: pandas<1.2 in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (1.1.5)
Requirement already satisfied: requests-toolbelt in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (0.9.1)
Requirement already satisfied: deepdiff in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (5.8.1)
Requirement already satisfied: deprecated in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (1.2.13)
Requirement already satisfied: netconan>=0.12.0 in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (0.12.3)
Requirement already satisfied: python-dateutil in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (2.8.2)
Requirement already satisfied: attrs>=18.1.0 in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (21.4.0)
Requirement already satisfied: requests in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (2.27.1)
Requirement already satisfied: simplejson in /opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages (from pybatfish) (3.17.6)
```

Any ideas? I've tried multiple python3 versions.
